query postsByUser($id: Int!, $paginationInput: PaginationInput!) {
	postsByUser(id: $id, paginationInput: $paginationInput) {
		total
		posts {
			id
			text
			author {
				id
				name
			}
			createdAt
		}
	}
}
